### ISSUE TITLE
Write a short blog post for fliegwerk.com

### ISSUE THREAD

**Issue by pklaschka** [fliegwerk/borg-distribute#1]
Could you please write a short entry in https://www.fliegwerk.com/projects for this project (or write it and send it to me so that I can publish it)?

Thank you very much in advance :slightly_smiling_face:

**Comment by Gnarflord** [comment]
No Problem, do you think the opening of the README (introduction and Philosophy) would suffice? I'll probably expand those points later on but as it stands my README contains more text than the whole code collection :)

**Comment by pklaschka** [comment]
@Gnarflord Sounds good. We'd need some sort of square logo for the project, though... If non-existent, the easiest thing would probably be to create an image with the initials, *BD*, on some background. That's up to you, though.

Should I add the post to the website or do you want to do it (credentials are in the website GitLab wiki...)?

**Comment by Gnarflord** [comment]
Donzo

**Comment by pklaschka** [comment]
Nice :+1:
